name: Publish image to DockerHub

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker HUB
      uses: docker/login-action@v2
      with:
        username: acselp123
        password: dckr_pat_L8cPhXZQi0WHjLiYPL86G7nwvmw

    - name: Build docker image
      run: docker build -t acselp123/learn_ci-cd:latest .

    - name: Push Docker image 
      run: docker push acselp123/learn_ci-cd:latest